// Class generated by GenerateExpressions.py script

namespace MoonSharp.Parsing.Expressions {
class Grouping : Expr {
private readonly Expr epxr;

public Grouping(Expr epxr) {
this.epxr = epxr;
}

public override T Accept<T>(IExprVisitor<T> visitor) => visitor.Visit(this);}
}
