// Class generated by GenerateExpressions.py script

namespace MoonSharp.Parsing.Expressions {
interface IExprVisitor<T> {
T Visit(Binary expr);
T Visit(Unary expr);
T Visit(Literal expr);
T Visit(Grouping expr);
}
}
