// Class generated by GenerateExpressions.py script

namespace MoonSharp.Parsing.Expressions {
class Unary : Expr {
private readonly Expr expr;
private readonly Token operator_;

public Unary(Expr expr, Token operator_) {
this.expr = expr;
this.operator_ = operator_;
}

public override T Accept<T>(IExprVisitor<T> visitor) => visitor.Visit(this);}
}
