// Class generated by GenerateExpressions.py script

namespace SharpTypus.Parsing.Expressions {
class Binary : Expr {
public Expr LeftExpr { get; }
public Expr RightExpr { get; }
public Token Operator_ { get; }

public Binary(Expr leftExpr, Expr rightExpr, Token operator_) {
LeftExpr = leftExpr;
RightExpr = rightExpr;
Operator_ = operator_;
}

public override T Accept<T>(IExprVisitor<T> visitor) => visitor.Visit(this);}
}
