// Class generated by GenerateExpressions.py script

namespace SharpTypus.Parsing.Expressions {
class Grouping : Expr {
public Expr Epxr { get; }

public Grouping(Expr epxr) {
Epxr = epxr;
}

public override T Accept<T>(IExprVisitor<T> visitor) => visitor.Visit(this);}
}
