// Class generated by GenerateExpressions.py script

namespace SharpTypus.Parsing.Expressions {
class Grouping : Expr {
public Expr Expr { get; }

public Grouping(Expr expr) {
Expr = expr;
}

public override T Accept<T>(IExprVisitor<T> visitor) => visitor.Visit(this);}
}
