// Class generated by GenerateExpressions.py script

namespace SharpTypus.Parsing.Expressions {
    class Literal : Expr {
        public Token Token { get; }

        public Literal(Token token) {
            Token = token;
        }

        public override T Accept<T>(IExprVisitor<T> visitor) => visitor.Visit(this);
    }
}
