// Class generated by GenerateExpressions.py script

namespace SharpTypus.Parsing.Expressions {
class Unary : Expr {
public Expr Expr { get; }
public Token Operator_ { get; }

public Unary(Expr expr, Token operator_) {
Expr = expr;
Operator_ = operator_;
}

public override T Accept<T>(IExprVisitor<T> visitor) => visitor.Visit(this);
public static bool operator ==(Unary left, Unary right) =>
left.Expr == right.Expr && left.Operator_ == right.Operator_;
public static bool operator !=(Unary left, Unary right) =>
!(left == right);
public override bool Equals(object obj) => obj is Unary ? (Unary)obj == this : false;
public override int GetHashCode() => (Expr, Operator_).GetHashCode();
}
}
