// Class generated by GenerateExpressions.py script

namespace SharpTypus.Parsing.Expressions {
class Unary : Expr {
public Expr Expr { get; }
public Token Operator_ { get; }

public Unary(Expr expr, Token operator_) {
Expr = expr;
Operator_ = operator_;
}

public override T Accept<T>(IExprVisitor<T> visitor) => visitor.Visit(this);}
}
