// Class generated by GenerateExpressions.py script

using SharpTypus.Parsing;
using SharpTypus.Expressions;
namespace SharpTypus.Statements {
class ExprStatement : Statement {
public Expr Expr { get; }

public ExprStatement(Expr expr) {
Expr = expr;
}

public override T Accept<T>(IStatementVisitor<T> visitor) => visitor.Visit(this);
public override bool Equals(object obj) {
if(!(obj is ExprStatement)) return false;
return ((ExprStatement)obj).Expr == this.Expr;
}
public override int GetHashCode() => (Expr).GetHashCode();
}
}
