// Class generated by GenerateExpressions.py script

using SharpTypus.Parsing;
namespace SharpTypus.Expressions {
class Literal : Expr {
public Token Token { get; }

public Literal(Token token) {
Token = token;
}

public override T Accept<T>(IExprVisitor<T> visitor) => visitor.Visit(this);
public override bool Equals(object obj) {
if(!(obj is Literal)) return false;
return ((Literal)obj).Token == this.Token;
}
public override int GetHashCode() => (Token).GetHashCode();
}
}
