// Class generated by GenerateExpressions.py script

using SharpTypus.Parsing;
namespace SharpTypus.Expressions {
class Variable : Expr {
public Token Name { get; }

public Variable(Token name) {
Name = name;
}

public override T Accept<T>(IExprVisitor<T> visitor) => visitor.Visit(this);
public override bool Equals(object obj) {
if(!(obj is Variable)) return false;
return ((Variable)obj).Name == this.Name;
}
public override int GetHashCode() => (Name).GetHashCode();
}
}
