// Class generated by GenerateExpression.py script

namespace MoonSharp.Parser.Expressions {
    class Binary : Expr {
        private readonly Expr leftExpr;
        private readonly Expr rightExpr;
        private readonly Token operator_;

        public Binary(Expr leftExpr, Expr rightExpr, Token operator_) {
            this.leftExpr = leftExpr;
            this.rightExpr = rightExpr;
            this.operator_ = operator_;
        }

        public override void Accept(IExprVisitor visitor) => visitor.Visit(this);
    }
}
