// Class generated by GenerateExpressions.py script

namespace MoonSharp.Parser.Expressions {
class Literal : Expr {
private readonly Token token;

public Literal(Token token) {
this.token = token;
}

public override void Accept(IExprVisitor visitor) => visitor.Visit(this);}
}
