// Class generated by GenerateExpression.py script

namespace MoonSharp.Parser.Expressions {
    class Unary : Expr {
        private readonly Expr expr;
        private readonly Token operator_;

        public Unary(Expr expr, Token operator_) {
            this.expr = expr;
            this.operator_ = operator_;
        }

        public override void Accept(IExprVisitor visitor) => visitor.Visit(this);
    }
}
